FROM ros:kinetic-ros-base-xenial

## follow instructions from http://emanual.robotis.com/docs/en/platform/turtlebot3/pc_setup/

ARG username=rosmaster
ARG groupid=1000
ARG userid=1000

# USE BASH
SHELL ["/bin/bash", "-c"]

# RUN LINE BELOW TO REMOVE debconf ERRORS (MUST RUN BEFORE ANY apt-get CALLS)
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

#### 6.1.2 
RUN apt-get install -y ros-kinetic-desktop-full ros-kinetic-rqt-*
RUN apt-get install -y python-rosinstall
RUN source ros_entrypoint.sh \
    && mkdir -p /catkin_ws/src \
    && cd /catkin_ws/src \
    && catkin_init_workspace \
    && cd /catkin_ws \
    && catkin_make
RUN echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc \
    && echo "export ROS_HOSTNAME=localhost" >> ~/.bashrc

#### 6.1.3
RUN  apt-get update -y && apt-get install -y ros-kinetic-joy \
    ros-kinetic-teleop-twist-joy ros-kinetic-teleop-twist-keyboard \
    ros-kinetic-laser-proc ros-kinetic-rgbd-launch \
    ros-kinetic-depthimage-to-laserscan ros-kinetic-rosserial-arduino \
    ros-kinetic-rosserial-python ros-kinetic-rosserial-server \
    ros-kinetic-rosserial-client ros-kinetic-rosserial-msgs ros-kinetic-amcl \
    ros-kinetic-map-server ros-kinetic-move-base ros-kinetic-urdf \
    ros-kinetic-xacro ros-kinetic-compressed-image-transport \
    ros-kinetic-rqt-image-view ros-kinetic-gmapping ros-kinetic-navigation \
    ros-kinetic-interactive-markers ros-kinetic-dynamixel-sdk ros-kinetic-turtlebot3-msgs \
    ros-kinetic-turtlebot3 ros-kinetic-cv-bridge ros-kinetic-vision-opencv
RUN cd /catkin_ws/src \
    && git clone https://github.com/RobotWebTools/web_video_server.git \
    && git clone  https://github.com/fkie/async_web_server_cpp.git  \
    
